server:
  port: 16001
spring:
  application:
    name: lbj-client-dis-redis

  # 配置数据源
#  datasource:
#    url: jdbc:mysql://192.168.160.165:13306/lbj_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&generateSimpleParameterMetadata=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@/11:1521/orcl
#    username: 111
#    password: 111

  # redis 配置
  redis:
    # 地址
    host: 192.168.160.165
    # 端口，默认为6379
    port: 16379
    # 密码
    #password: ****
    # 连接超时时间
    timeout: 200s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 2
        # 连接池的最大数据库连接数
        max-active: 5
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


# 配置日志级别
logging:
  level:
    #    root: info
    root: debug
  file: ./data/log/${spring.application.name}.log




