server:
  port: 16002
spring:
  application:
    name: lbj-client-kafka-consumer
#  #热部署生效
#  devtools:
#    restart:
#      enabled: true
#      #设置重启的目录,添加那个目录的文件需要restart
#      additional-paths: src/main/java
#  # 声明生效的配置文件
#  profiles:
#    # 正式环境
#    active: pro

  # Kafka配置
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers:  192.168.160.165:19092  # kafka服务地址和端口
#          auto-create-topics: true # 如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
#      bindings:
#        input: #input是接收，注意这里不能再像前面一样写output了
#          destination: stream-demo #消息接收的目的地

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - 192.168.162.165:19092
      bindings:
        input:
          binder: kafka
          destination: test1
          content-type: text/plain
          group: input-group-1
        my-in:
          binder: kafka
          destination: mytest
          content-type: text/plain
          group: input-group-2

# 配置日志级别
logging:
  level:
    #    root: info
    root: debug
  file: ./data/log/${spring.application.name}.log







