apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-client-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nx-client-demo
      release: stabel
  template:
    metadata:
      labels:
        app: nx-client-demo
        release: stabel
        env: test
    spec:
      containers:
        - name: nx-client-demo
          image: 192.168.160.232:11005/library/nx-client-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 16001

# ----------------------------
apiVersion: v1
kind: Service
metadata:
  name: nx-client-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: nx-client-demo
    release: stabel
  ports:
    - name: http
      port: 16001
      targetPort: 16001
      nodePort: 31001
